### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by TianxingWu** [camenduru/FreeInit-colab#2]
Thanks for creating the colab for testing. Some bugs in my original implementation have been fixed recently, please refer to the following commits in case you wanna take a look :)

- https://github.com/TianxingWu/FreeInit/commit/173aeb2196c275b506d063e05c7c2d1f1a36b3de
- https://github.com/TianxingWu/FreeInit/commit/4646af6ef730d082861de92476df2ff1b5d0ba23 (critical resolution bug in gradio demo)
- https://huggingface.co/spaces/TianxingWu/FreeInit/commit/fa69421fca1fe8fd5eba9c902720be66ddb343fa

**Comment by TianxingWu** [comment]
And BTW the parameter `num_iters` in the colab should be larger than 1, recommended 3-5. Setting `num_iters` to 1 means no FreeInit at all (that would be vanilla AnimateDiff).

**Comment by camenduru** [comment]
thanks ❤ I updated the colabs
